import { Payment, columns } from "./columns";
import { DataTable } from "./data-table";

async function getData(): Promise<Payment[]> {
  return [
    {
      id: "1",
      name: "Qonto",
      domainName: "qonto.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 1400,
      linkedin: "qonto",
      address: "OLINDA SAS, 18 cmkdslhdfjhv dsnckdiuvcbdruihnsdv u hiusd gfsuoyujfbvet ygiufgukdj",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "3",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "4",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "5",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
    {
      id: "2",
      name: "Google",
      domainName: "google.com",
      accountOwner: "",
      creationDate: "Nov 23 2023 21:08",
      employees: 72000,
      linkedin: "google",
      address: "1600 cmkdslhdfjhv",
    },
  ];
}

export default async function Dashboard() {
  const data = await getData();

  return (
    <div className="container mx-auto mt-5">
      <DataTable columns={columns} data={data} />
    </div>
  );
}
